<a href="https://colab.research.google.com/github/Dhayanidhi-96/Dhayanidhi-96.github.io/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY**

Numpy is a multidimensional array that

can store 1D,2D,3D etc

**HOW ARE LIST DIFFERENT FROM NUMPY**



1.   Lists are slow in processing
2.   List item are fast in processing and numpy uses lesser memory
3.   Nmupy uses contigous memory
4.   SIMD -Single instruction multiple data (ie insted of dooing one addition at time it do all in one time)
5.  Efffectivee use of cache


**APPLICATIONS OF NUMPY:**



*   Mathemetics
*   Ploting
*   store images using numpy
*   Ml applications











In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
#ARRAY HAVE LIST WITHIN THE LIST
b = np.array([[12,34,45,56],[12,23,34,56]])
print(b)

[[12 34 45 56]
 [12 23 34 56]]


In [ ]:
#to ge dimension use example to get the dimensions of a we can write a.ndim

a.ndim
b.ndim

2

In [ ]:
#Get shape
b.shape

(2, 4)

In [ ]:
#Get tyoe
b.dtype

dtype('int64')

In [ ]:
b.itemsize

8

In [ ]:
a =np.array([[23,45,5,65,76,54],[23,34,56,16,48,56]])
print(a)
a.shape

[[23 45  5 65 76 54]
 [23 34 56 16 48 56]]


(2, 6)

In [ ]:
a[0,2]

5

In [ ]:
#get a specfic row
a[0,:]

array([23, 45,  5, 65, 76, 54])

In [ ]:
a[:,2]

array([ 5, 56])

In [ ]:
#get a little more fancy with[start nindex:endindex:step size]
a[0,1:-1:2]

array([45, 65])

In [ ]:
a[0,2] = 25
print(a)


[[23 45 25 65 76 54]
 [23 34 56 16 48 56]]


In [ ]:
b= np.array([[[1,2,3,4],[2,3,4,5]],[[3,4,5,6],[5,6,7,8]]])
print(b)

[[[1 2 3 4]
  [2 3 4 5]]

 [[3 4 5 6]
  [5 6 7 8]]]


In [ ]:
b[1,0,2]

5

In [ ]:
b[:,1,:]

array([[2, 3, 4, 5],
       [5, 6, 7, 8]])

**Initializing Different Types of Arrays**


In [ ]:
#all 0s matrix
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((3,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
np.zeros((1,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [ ]:
#all is matrix
np.ones((3,3),dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [ ]:
np.full((2,2),96,dtype='float32')

array([[96., 96.],
       [96., 96.]], dtype=float32)

In [ ]:
#random decimal number
np.random.rand(4,2)

array([[0.9743601 , 0.72490812],
       [0.21343993, 0.26946062],
       [0.38659902, 0.74358191],
       [0.09086904, 0.98410093]])

In [ ]:
#random interger value
np.random.randint(1000,size=(3,3))

array([[421, 996, 852],
       [ 27, 667, 519],
       [855, 898, 100]])

In [ ]:
#random interger value
np.random.randint(500,1000,size=(3,3))

array([[879, 510, 744],
       [908, 514, 686],
       [865, 942, 722]])

In [ ]:
#to create identoty matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
arr = np.array([[[1,2,3]]])
r1 = np.repeat(arr,4,axis=0)
print(r1)

[[[1 2 3]]

 [[1 2 3]]

 [[1 2 3]]

 [[1 2 3]]]


In [ ]:
output =np.ones((5,5))
print(output)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
z = np.zeros((3,3))
z[1,1] = 9
print(z)



[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [ ]:
output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**MATHAMETICS**

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a+5

array([6, 7, 8, 9])

In [ ]:
a//2

array([0, 1, 1, 2])

**Linear algebra**

In [ ]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
c = np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

In [ ]:
##Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

#Determinant
#Trace
#Singular Vector Decomposition
#Eigenvalues
#Matrix Norm
#Inverse
#Etc...

**Statistics**

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats,axis=1)

array([1, 4])

In [ ]:
np.max(stats,axis=1)

array([3, 6])

**Reorganizing array**

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((1,8))
print(after)
#

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]]


In [ ]:
#vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
#Horizontal stacking
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

**Miscellaneous**

load data from file

In [ ]:
matrix = np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20],
                   [21, 22, 23, 24, 25],
                   [26, 27, 28, 29, 30]])
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [ ]:
matrix[2:4,3:]

array([[14, 15],
       [19, 20]])

In [ ]:
matrix[[0,1,2,3,4],[0,1,2,3,4]]

array([ 1,  7, 13, 19, 25])

In [ ]:
matrix[[4,5],0:2]

array([[21, 22],
       [26, 27]])

In [ ]:
matrix[1:5,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])